server {
    listen 8080;
    root /usr/share/nginx/html/;
    index index.html;
    error_page 403 404 @error4xx;
    location /template-operator-v2-docs/ {
        rewrite ^/template-operator-v2-docs/(.*)$ /$1 last;
    }
    location = /template-operator-v2-docs {
        return 301 /template-operator-v2-docs/;
    }
    location @error4xx {
        rewrite ^/([^/]*) /$1/404.html last;
    }
    # redirects issued by nginx will be relative
    absolute_redirect off;
}
